---
deployment:
  tasks:
    - export DEPLOYPATH=/home/chanelgl/public_html/
    - /bin/cp /home/chanelgl/repositories/ChanelQuesnel/index.html $DEPLOYPATH
    - /bin/cp -R /home/chanelgl/repositories/ChanelQuesnel/images $DEPLOYPATH
    - /bin/cp -R /home/chanelgl/repositories/ChanelQuesnel/js $DEPLOYPATH
    - /bin/cp -R /home/chanelgl/repositories/ChanelQuesnel/css $DEPLOYPATH