---
deployment:
  tasks:
    - export DEPLOYPATH=/home/chanelgl/public_html/
    - /bin/cp ChanelQuesnel/index.html $DEPLOYPATH
    - /bin/cp -R ChanelQuesnel/images $DEPLOYPATH
    - /bin/cp -R ChanelQuesnel/js $DEPLOYPATH
    - /bin/cp -R ChanelQuesnel/css $DEPLOYPATH