---
deployment:
  tasks:
    - export DEPLOYPATH=/home/chanelgl/public_html/
    - /repositories/ChanelQuesnel index.html $DEPLOYPATH
    - /repositories/ChanelQuesnel -R images $DEPLOYPATH
    - /repositories/ChanelQuesnel -R js $DEPLOYPATH
    - /repositories/ChanelQuesnel -R css $DEPLOYPATH